#!/bin/bash

echo Installing Vim 8.2...

sudo add-apt-repository ppa:jonathonf/vim
sudo apt update
sudo apt install vim

echo Installing Vim Plug...

curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

echo Installing Vim plugins...

vim -c ":PlugInstall<cr>"

echo Done!
